### ISSUE TITLE
SHERPA/RoMEO API v.2

### ISSUE THREAD

**Issue by Rekyt** [ropensci/rromeo#52]
SHERPA/RoMEO just released a v2 of their API https://v2.sherpa.ac.uk/romeo/api.html
It's a pre-release but should migrate all functions to v2 of the API at least experimental.
The API now returns JSON and give access to publisher_policy information in addition to journal and publisher information.

We can look here https://app.swaggerhub.com/apis/gobfrey/v2.sherpa-api/2.1 to see examples of queries

**Comment by Rekyt** [comment]
That may also explain why the older API does not work without an API key as SHERPA/RoMEO should close the access to the old API.

**Comment by Rekyt** [comment]
I started experimenting in the `v2_experiment` branch ropensci/rromeo@6d59da07689d5783dd6402a7daeee720d78eb8b5
We should develop a new `rromeo` version in a new branch, and merge once the V2 of the API is released.

**Comment by Rekyt** [comment]
SHERPA has announced that v1 of API will be decommissioned on Tuesday 14 April 2020
we should have v2 ready for that date.

**Comment by Rekyt** [comment]
Okay, better late than never SHERPA/RoMEO has a complete and stable documentation of [their API](https://v2.sherpa.ac.uk/api/metadata-schema.html)
From this we could rebuild `rromeo`.

**Comment by p-value-sharma** [comment]
> Okay, better late than never SHERPA/RoMEO has a complete and stable documentation of [their API](https://v2.sherpa.ac.uk/api/metadata-schema.html)
> From this we could rebuild `rromeo`.

Hi @Rekyt, 

Great to see this thread, I just downloaded rromeo and it was not working. 

Even trying rromeo::rr_api_version() would give an NA and trying rr_journal_find(name = "Biostatistics", qtype = "contains") as an example would give "Error: The API endpoint could not be reached. Please try again later."

I logged into to ask whether the developers were aware of what might be causing these issues, but looks like the team is on it.

**Comment by Rekyt** [comment]
Thank you so much @p-value-sharma for the interest !
Indeed we know the issue but have currently limited time to work on it so it'll probably take a little time.
We however welcome Pull Request!

**Comment by maelle** [comment]
This package will be archived with the agreement of the authors @Rekyt @Bisaloo. 

rOpenSci archival guidance https://devdevguide.netlify.app/evolution.html#archivalguidance
