### ISSUE TITLE
Vignette / pkgdown error

### ISSUE THREAD

**Issue by jeroen** [ropensci/rromeo#57]
As of recently, the pkgdown site fails: https://dev.ropensci.org/job/rromeo/lastBuild/console

Trying locally the error seems to be related to the @sckott  `vcr` package:

<img width="477" alt="Screen Shot 2019-12-04 at 1 43 26 PM" src="https://user-images.githubusercontent.com/216319/70143508-1ae2c580-169c-11ea-8d50-b48efa1235b7.png">

**Comment by sckott** [comment]
@jeroen  i assume the dev server is using whatever's on master for each repo? i did have an error like that in vcr's test suite yesterday i think, but that should be fixed

**Comment by sckott** [comment]
recent push of vcr just now should fix this, recent changes weren't accounting for cached files created with older versions of vcr, should work now

**Comment by jeroen** [comment]
Thanks, looks like that fixed it.
